apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/agent: "true"
spec:
  nodeSelector:
    role: platform-exec
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest-jdk17
      workingDir: /home/jenkins/agent
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    - name: docker
      image: docker:dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
    - name: helm
      image: alpine/helm:latest
      command:
        - sleep
      args:
        - "99999"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
  volumes:
    - name: docker-storage
      emptyDir: {}
